### ISSUE TITLE
Open toonz project crash

### ISSUE THREAD

**Issue by YankaWarm** [turtletooth/tahoma#145] opened 2020-09-07 09:42 UTC
I made my project in Tahoma, after that i open this project in open toonz and now tahoma cant open this my project more (
Tahoma say me: "has ben trouble with open this project" and crash (((

**Describe the bug**

**To Reproduce**
List steps to reproduce the behavior.
1.
2.
3.

**Expected behavior**

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]
 - Tahoma Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by jeremybullock** [comment] 2020-09-07 18:14
I think this is probably related to a bug that exists in OpenToonz that has been fixed on this side.  I can confirm if you are willing to share the scene file.

**Comment by artisteacher** [comment] 2020-09-07 19:47
Is it the <> or <n> thing? Maybe they should be automatically deleted from a scene upon loading if they exist, in case OT projects are used.

**Comment by manongjohn** [comment] 2020-09-07 19:50
Tahoma can handle the <n> issue by ignoring it, but not the <> if that is the cause of it. I had trouble with skipping <>, which I thought was a rare issue. The <n> seemed more prevalent. I will try and revisit ignoring <> if that is the case.

**Comment by jeremybullock** [comment] 2020-09-10 04:34
@YankaWarm Please share the project file if you able.  We are unable to fix issues that we can't duplicate.

**Comment by jeremybullock** [comment] 2020-09-26 07:15
Closing for now.  If more information comes along I'd still love to help.

**Closed by jeremybullock** 2020-09-26 07:15 UTC
Labels: bug
