### ISSUE TITLE
Maximized version of Tahoma not full screen (Bug Report)

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma#230] opened 2020-09-26 19:18 UTC
This was working fine before, but something has suddenly caused this, and I can't figure out what (nor how to fix it).

When I launch Tahoma now, it makes the main (Tahoma) window smaller than the monitor screen size, despite the window being maximized.  It doesn't seem to be related to the size the main window is when it's in Restore Down mode.

Manually stretching each of the window edges to the edges of the monitor screen (in Restore Down mode) results in the screen staying fullscreen when you click the Maximize button again... but only for that session.  Relaunching Tahoma reverts it back to it's 'windowed' state, despite launching maximized.

I can't seem to get anything to fix it.  Any theories or suggestions?

Does Tahoma have some sort of config file that stores the (assumed) monitor resolution?  I get the feeling it THINKS my monitor is now smaller than it is in reality... or at least that's my current theory.

My other programs are launching into fullscreen properly, so it seems specific to Tahoma.

![TahomaNotMaximized](https://user-images.githubusercontent.com/71803483/94348585-7a370b00-000b-11eb-8291-65f12cc0d88d.JPG)

Win7Pro 32gigs RAM NVidia Tahoma1.0

**Comment by RodneyBaker** [comment] 2020-09-27 01:34
Duplicate of https://github.com/turtletooth/tahoma/issues/229?

**Comment by ladlon** [comment] 2020-09-27 03:35
Hi.  That's my post as well.  The first was intended as just a question, as I wasn't fully sure it was a bug, or just some Win7 thing.

After a bit more experimenting (and seeing that all my other programs were behaving fine), I was fairly confident that it may be a specific Tahoma bug (and it seems like JeremyBullock knows what it might be).

I tried making a bug report post, but for some reason, the bug label didn't stick.

HA!  Just as I wrote that, Jeremy added the Bug label, as I requested!  (Thanks Jeremy)

**Comment by jeremybullock** [comment] 2020-09-27 03:43
This is fixed and will be merged tonight in #236

**Closed by jeremybullock** 2020-09-27 03:43 UTC
Labels: bug

**Comment by ladlon** [comment] 2020-09-27 03:48
Awesome!  Thanks, Jeremy.

I wanted to say (but wasn't sure where it was best to post it) that I'm really impressed with the quick and helpful responses of the people here, coders and users alike.  OpenToonz/Tahoma were a really great surprise to me, while I was looking for some alternative to Moho.  I'm really impressed with what has been achieved so far, and am really looking forward to see how it evolves (and am very thankful to those working so hard on this software).

So, thanks to all!
